default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: morigakuto
  password: 
  host: localhost

development:
  <<: *default
  database: myapi_development

test:
  <<: *default
  database: myapi_test

production:
  <<: *default
  database: myapi_production
  username: myapi
  password: <%= ENV['MYAPI_DATABASE_PASSWORD'] %>