services:
  backend:
    build: ./backend
    ports:
      - 3001:3000
    volumes:
      - ./backend:/app
    environment:
      - RAILS_ENV=development
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:14
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password